version: '3.8'

services:
  meterapi:
    build: .
    container_name: meterapi
    ports:
      - "5000:8080"
    depends_on:
       meter_db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=meter_db;Port=5432;Database=identity_db;Username=postgres;Password=password


  orderapi:
    build: ../DemoOrder
    container_name: orderapi
    ports:
      - "5001:8080"
    depends_on:
      order_db:
          condition: service_healthy
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Host=order_db;Port=5432;Database=identity_db;Username=postgres;Password=password   


  meter_db:
    image: postgres:15
    container_name: meter_db
    restart: always
    environment:
      POSTGRES_DB: identity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - meter_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  order_db:
    image: postgres:15
    container_name: order_db
    restart: always
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx :
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - meterapi
      - orderapi


volumes:
  meter_pgdata:
  order_pgdata: